// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'Your_web_api_key',
    appId: 'Your_web_app_id',
    messagingSenderId: 'Your_web_messaging_sender_id',
    projectId: 'Your_web_project_id',
    authDomain: 'Your_web_auth_domain',
    storageBucket: 'Your_web_storage_bucket',
    measurementId: 'Your_web_measurement_id',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'Your_android_api_key',
    appId: 'Your_android_app_id',
    messagingSenderId: 'Your_android_messaging_sender_id',
    projectId: 'Your_android_project_id',
    storageBucket: 'Your_android_storage_bucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'Your_ios_api_key',
    appId: 'Your_ios_app_id',
    messagingSenderId: 'Your_ios_messaging_sender_id',
    projectId: 'Your_ios_project_id',
    storageBucket: 'Your_ios_storage_bucket',
    iosBundleId: 'Your_ios_bundle_id',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'Your_macos_api_key',
    appId: 'Your_macos_app_id',
    messagingSenderId: 'Your_macos_messaging_sender_id',
    projectId: 'Your_macos_project_id',
    storageBucket: 'Your_macos_storage_bucket',
    iosBundleId: 'Your_macos_bundle_id',
  );
}
