// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1wgZs2bRLq6fiop_nxCcgFcCxO7jIioY',
    appId: '1:192145375261:web:a9c6ac6d86f1beba5186f4',
    messagingSenderId: '192145375261',
    projectId: 'ymca-all-in-one',
    authDomain: 'ymca-all-in-one.firebaseapp.com',
    storageBucket: 'ymca-all-in-one.appspot.com',
    measurementId: 'G-2T4YZ7Q2HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMNFVrgQcxOGwKaefuDWeO-sHdjvaQNHU',
    appId: '1:192145375261:android:624090de7a25ff125186f4',
    messagingSenderId: '192145375261',
    projectId: 'ymca-all-in-one',
    storageBucket: 'ymca-all-in-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSBjN0Xw1RZwpEisWGgyl7GiN2qBtOQhg',
    appId: '1:192145375261:ios:400d4745054d52845186f4',
    messagingSenderId: '192145375261',
    projectId: 'ymca-all-in-one',
    storageBucket: 'ymca-all-in-one.appspot.com',
    iosBundleId: 'com.shubham.ymcaAllInOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSBjN0Xw1RZwpEisWGgyl7GiN2qBtOQhg',
    appId: '1:192145375261:ios:0dfcd53d03bee42c5186f4',
    messagingSenderId: '192145375261',
    projectId: 'ymca-all-in-one',
    storageBucket: 'ymca-all-in-one.appspot.com',
    iosBundleId: 'com.shubham.ymcaAllInOne.RunnerTests',
  );
}
